version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: user-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./db/users:/data/db
